# Generated by Django 4.2.19 on 2025-03-06 03:27

from django.db import migrations

def populate_wine_regions(apps, schema_editor):
    WineRegion = apps.get_model('climate_api', 'WineRegion')
    WineRegion.objects.create(name="McLaren Vale, South Australia", latitude=-35.22, longitude=138.54)
    WineRegion.objects.create(name="Margaret River, Western Australia", latitude=-33.96, longitude=115.08)
    WineRegion.objects.create(name="Mornington, Victoria", latitude=-38.22, longitude=145.04)
    WineRegion.objects.create(name="Coonawarra, South Australia", latitude=-37.29, longitude=140.83)
    WineRegion.objects.create(name="Yarra Valley, Victoria", latitude=-37.75, longitude=145.10)

class Migration(migrations.Migration):

    dependencies = [
        ('climate_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_wine_regions),
    ]
