# Generated by Django 4.2.19 on 2025-03-07 04:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate_api', '0002_populate_wine_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wineregion',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ClimateInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_time_of_year_start_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('optimal_time_of_year_end_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('performance_score_last_10_years', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('optimal_conditions_percentage_last_30_years', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('wine_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_api.wineregion')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_mean', models.DecimalField(decimal_places=1, max_digits=5)),
                ('relative_humidity_mean', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precipitation_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wine_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate_api.wineregion')),
            ],
            options={
                'indexes': [models.Index(fields=['wine_region', 'date'], name='climate_api_wine_re_c5c332_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='climatemetrics',
            constraint=models.UniqueConstraint(fields=('wine_region', 'date'), name='unique_wine_region_date'),
        ),
        migrations.AddIndex(
            model_name='climateinsights',
            index=models.Index(fields=['wine_region'], name='climate_api_wine_re_01a874_idx'),
        ),
        migrations.AddIndex(
            model_name='climateinsights',
            index=models.Index(fields=['created_at'], name='climate_api_created_bb39f1_idx'),
        ),
    ]
