# Generated by Django 4.2.19 on 2025-03-09 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_api', '0003_alter_wineregion_name_climateinsights_climatemetrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climateinsights',
            name='performance_score_last_10_years',
        ),
        migrations.AddField(
            model_name='climateinsights',
            name='past_10_years_percentage_days_in_optimal_humidity_range',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='climateinsights',
            name='past_10_years_percentage_days_in_optimal_temp_range',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='climateinsights',
            name='past_10_years_winter_precipitation_total',
            field=models.DecimalField(decimal_places=20, default=0.0, max_digits=30),
        ),
    ]
