# Generated by Django 4.2.19 on 2025-03-09 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_api', '0004_remove_climateinsights_performance_score_last_10_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateinsights',
            name='optimal_time_of_year_end_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='climateinsights',
            name='optimal_time_of_year_start_month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
