# Generated by Django 4.2.19 on 2025-03-09 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_api', '0006_alter_climateinsights_optimal_conditions_percentage_last_30_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climateinsights',
            name='optimal_conditions_percentage_last_30_years',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='climateinsights',
            name='past_10_years_percentage_days_in_optimal_humidity_range',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='climateinsights',
            name='past_10_years_percentage_days_in_optimal_temp_range',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='climateinsights',
            name='past_10_years_winter_precipitation_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
