# Generated by Django 4.2.19 on 2025-03-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate_api', '0007_alter_climateinsights_optimal_conditions_percentage_last_30_years_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='climatemetrics',
            name='unique_wine_region_date',
        ),
        migrations.RemoveIndex(
            model_name='climatemetrics',
            name='climate_api_wine_re_c5c332_idx',
        ),
        migrations.RenameField(
            model_name='climatemetrics',
            old_name='date',
            new_name='metric_date',
        ),
        migrations.AddIndex(
            model_name='climatemetrics',
            index=models.Index(fields=['wine_region', 'metric_date'], name='climate_api_wine_re_50d6a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='climatemetrics',
            constraint=models.UniqueConstraint(fields=('wine_region', 'metric_date'), name='unique_wine_region_metric_date'),
        ),
    ]
